import { useState } from "react";
import { useNavigate } from "react-router";
import { Shield, Lock, User, Key, ArrowLeft, Send, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { motion } from "motion/react";
import "@/styles/ForgotPassword.css";

const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:5000/api";

export function ForgotPassword() {
  const navigate = useNavigate();
  const [step, setStep] = useState<"request" | "reset">("request");
  const [loading, setLoading] = useState(false);
  const [username, setUsername] = useState("");
  const [token, setToken] = useState("");
  const [newPassword, setNewPassword] = useState("");

  const handleRequest = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!username.trim()) return toast.error("Enter your username or email.");

    setLoading(true);
    try {
      const res = await fetch(`${API_URL}/auth/forgot-password`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: username.trim() }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success("Security token requested.");
        setStep("reset");
      } else {
        toast.error(data.error || "Account not found.");
      }
    } catch {
      toast.error("Network error. Verify server status.");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token.trim() || !newPassword.trim()) return toast.error("All fields required.");

    setLoading(true);
    try {
      const res = await fetch(`${API_URL}/auth/reset-password`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token: token.trim(), newPassword }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success("Identity verified. Password updated.");
        navigate("/admin/login");
      } else {
        toast.error(data.error || "Invalid token.");
      }
    } catch {
      toast.error("Operation failed.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="forgot-password-container">
      <div className="bg-grid-layer">
        <div className="bg-grid-pattern" />
      </div>

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="fp-card-wrapper"
      >
        <div className="fp-card">
          <div className="fp-header">
            <div className="fp-icon-box">
              <Key size={24} />
            </div>
            <h1 className="fp-title">Security Recovery</h1>
            <p className="fp-subtitle">
              Internal Clearance Protocol
            </p>
          </div>

          {step === "request" ? (
            <motion.form initial={{ x: -20, opacity: 0 }} animate={{ x: 0, opacity: 1 }} onSubmit={handleRequest} className="fp-form">
              <div>
                <label className="fp-input-label">Account Identifier</label>
                <div className="fp-input-wrapper">
                  <User size={15} className="fp-input-icon" />
                  <input
                    type="text"
                    value={username}
                    onChange={e => setUsername(e.target.value)}
                    placeholder="Username or System Email"
                    className="fp-input"
                  />
                </div>
              </div>
              <button
                type="submit"
                disabled={loading}
                className="fp-submit-btn blue"
              >
                {loading ? "Initializing..." : "Request Security Token"}
              </button>
            </motion.form>
          ) : (
            <motion.form initial={{ x: 20, opacity: 0 }} animate={{ x: 0, opacity: 1 }} onSubmit={handleReset} className="fp-form">
              <div className="fp-info-box">
                <p className="fp-info-text">
                  Verification pending. Enter the security token generated by the server terminal.
                </p>
              </div>
              <div>
                <label className="fp-input-label">Security Token</label>
                <div className="fp-input-wrapper">
                  <Shield size={15} className="fp-input-icon" />
                  <input
                    type="text"
                    value={token}
                    onChange={e => setToken(e.target.value)}
                    placeholder="PROTOCOL-XXXXX"
                    className="fp-input token-input"
                  />
                </div>
              </div>
              <div>
                <label className="fp-input-label">New Password</label>
                <div className="fp-input-wrapper">
                  <Lock size={15} className="fp-input-icon" />
                  <input
                    type="password"
                    value={newPassword}
                    onChange={e => setNewPassword(e.target.value)}
                    placeholder="••••••••"
                    className="fp-input"
                  />
                </div>
              </div>
              <button
                type="submit"
                disabled={loading}
                className="fp-submit-btn emerald"
              >
                {loading ? "Re-encrypting..." : "Restore Account Access"}
              </button>
            </motion.form>
          )}

          <button
            onClick={() => navigate("/admin/login")}
            className="fp-back-btn"
          >
            <ArrowLeft size={12} />
            Back to Login
          </button>
        </div>
      </motion.div>
    </div>
  );
}
